{% set name = "kfp-tekton" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kfp-tekton-{{ version }}.tar.gz
  sha256: ef3bbe90af9097e1e492f8ceeda0ac1ccd252c7f4da140781ec5ebf6cf803b2e

build:
  number: 0
  noarch: python
  entry_points:
    - dsl-compile-tekton = kfp_tekton.compiler.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5.3
    - pip
    - requests
  run:
    - python >=3.5.3
    - kfp ==1.1.2

test:
  imports:
    - kfp_tekton
    - kfp_tekton.compiler
  commands:
    - dsl-compile-tekton --help
  requires:
    - pip

about:
  home: https://github.com/kubeflow/kfp-tekton/
  summary: Tekton Compiler for Kubeflow Pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ckadner
    - Tomcli
    - animeshsingh
